/* A complete, realistic plan — the shape the printed page has to carry. */
export const FULL_PLAN = {
 schema:2, updatedAt:"2026-10-08T09:00:00.000Z", pace:"sitting",
 progress:{furthestStep:7,completed:[1,2,3,4,5,6,7]}, yearEnding:{word:"Rebuilding"},
 step1:{wins:[{id:"w1",text:"Finally had the conversation about my role",enabler:"I prepared properly"},
              {id:"w2",text:"Shipped the side project",enabler:"Small Saturdays"}],
        challenges:[{id:"c1",text:"A project that ran six months late",lesson:"I say yes too quickly"},
                    {id:"c2",text:"Left it too long to ask for help",lesson:"Asking early saves months"}],
        wheel:{career:7,money:6,health:3,fun:2,family:8,friends:5,growth:6,purpose:4},
        energy:{gave:["Long walks with no phone"],drained:["Back-to-back video calls"]}},
 step2:{values:[{slug:"integrity",name:"Integrity",source:"list",alignment:4},
                {slug:"family",name:"Family",source:"list",alignment:2},
                {slug:"creativity",name:"Creativity",source:"list",alignment:1},
                {slug:"courage",name:"Courage",source:"list",alignment:3},
                {slug:"growth",name:"Growth",source:"list",alignment:4},
                {slug:"freedom",name:"Freedom",source:"list",alignment:3}],
        compromise:"I say family comes first, then worked most weekends in the spring.",
        lettingGo:[{id:"l1",text:"Checking my phone in bed",bucket:"habit",releasedAt:"2026-01-01"},
                   {id:"l2",text:"Chairing the committee",bucket:"commitment",releasedAt:null},
                   {id:"l3",text:"I should be further along by now",bucket:"should",releasedAt:"2026-01-01"}],
        closingLine:"I learned to ask for help, eventually."},
 step3:{headline:"Left the job that was draining me, and found my weekends again.",
        detail:"I sleep properly. I see my friends every week. Work feels like mine again."},
 step4:{word:"Steady",themes:[{id:"t1",text:"Protect my energy"},{id:"t2",text:"Build something of my own"},{id:"t3",text:"Show up for my people"}]},
 step5:{goals:[{id:"g1",themeId:"t1",done:"Sleep seven hours a night, most nights",valueSlug:"family",why:"Everything gets harder when I'm tired",date:"2027-03",habit:"Phone out of the bedroom, lights out by eleven",firstStep:"Buy an alarm clock"},
               {id:"g2",themeId:"t2",done:"Ten paying customers for my side project",valueSlug:"creativity",why:"I want to make something that's mine",date:"2027-06",habit:"Two hours every Saturday morning",firstStep:"Talk to three people who might buy it"},
               {id:"g3",themeId:"t3",done:"See my closest friends every month",valueSlug:"family",why:"They keep me honest",date:"2027-01",habit:"One standing date a month",firstStep:"Put four dates in the diary"}],
        priorityGoalId:"g1"},
 step6:{ifThen:{g1:{if:"...I'm still wired at eleven",then:"...read a paper book instead of my phone"},
                g2:{if:"...work runs late on a Friday",then:"...do one hour on Sunday instead"},
                g3:{if:"...a month slips by",then:"...text them that day, not next week"}},
        corner:{who:["friend","coach"],ask:"Ask Alex to check in on my Saturday mornings once a month."}},
 step7:{overrides:{},noteToFutureSelf:"Go gently, and keep going.",livesAt:"On the fridge",
        checkIns:["2027-01-08","2027-04-08","2027-07-08","2027-10-08"]}
};
